version: '1'

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - ensolvers_network
    volumes:
      - ./backend:/app 
      - /app/node_modules
    command: sh -c "npm install && npm run migrations:run && npm run start:dev"

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3001:5173
    networks:
      - ensolvers_network
    volumes:
      - ./frontend:/app 
      - /app/node_modules

  postgres:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - ensolvers_network
    volumes:
      - ./backend/postgres_data:/var/lib/postgresql/data
networks:
  ensolvers_network:
    driver: bridge
